### PR TITLE
Un-break the docs

### PR DESCRIPTION
**Pull request by benborgers**
## What Broke

In https://github.com/glow-xyz/nftoken/pull/155, I merged this change to `_app.tsx`: 

https://github.com/glow-xyz/nftoken/blob/782b1086831083d9f0f4e5944e0b4050ae07adc7/docs/pages/_app.tsx#L25-L27

This should’ve been `/docs` instead of `docs`, which meant that the `<DocsPage />` layout didn’t render when it was supposed to. `DocsPage` includes the sidebar, mobile nav, and `GlowProvider`, which caused the missing sidebar, mobile nav not working, and minting not working. 

Before merging the new NFT detail page I wasn’t careful enough about check the docs part of the site, so I didn’t notice that the docs were broken. 

## Fix

- Replaced `docs` with `/docs`. 
- Moved the mobile nav to `<Header />`, so every time the mobile nav menu button is rendered in the header there’s also an actual mobile nav. 

## Test Checklist

Tested using https://nftoken-git-fix-revert.luma-dev.com

- [x] Splash page looks good in desktop and mobile. 
- [x] “Learn more” and “Create an NFT” links work. 
- [x] Docs logo goes to Overview. 
- [x] GitHub link works. 
- [x] Forward and back buttons on each page go to the correct place. 
- [x] Glow and Twitter buttons in footer work. 
- [x] Sidebar and header show on docs pages and are position: sticky when scrolling. 
- [x] Docs look good on mobile. 
- [x] Mobile nav works on docs and on NFT detail page. 
- [x] Mobile nav works even when scrolled down the page. 
- [x] Mobile nav closes when a link is clicked. 
- [x] Page is not scrollable while mobile nav is open. 
- [x] Mobile nav links work. 
- [ ] Connect/disconnect wallet works on Live Minting Demo, and so does filling out the form and clicking Create NFT. 
- [x] Live Minting Demo looks good on mobile. 
- [x] Code blocks are legible and can be copied via button in top right corner. 
- [x] NFT detail page has header whose mobile nav can be expanded, but no sidebar on desktop. 
- [x] NFT detail page’s mobile nav works when opened while scrolled partially down the page. 
- [x] NFT detail page looks good on mobile. 
- [x] Copying Solana addresses on NFT detail page works and causes a success toast to appear. 
- [x] Clicking logo on NFT detail page goes to Overview. 
- [x] Clicking links in mobile nav on NFT detail page works. 
- [x] All pages look good when browser font size is increased (in settings, not cmd+/cmd-). 
- [x] All pages look good in dark mode. 
- [x] All pages look good in Safari. 
- [x] All pages look good in Firefox. 

Let me know if there’s anything else I should add to this checklist! 

## Outstanding Problems

- [ ] I can’t connect wallet for the Live Minting Demo on iOS Safari. Is it a problem with it being a Vercel staging URL?

### CODE REVIEW

**Review by vpontis — APPROVED** [review]
Nice! And comprehensive checklist. I think for future PRs you can run thru the main things, you don't need such a long checklist (like you don't need to check the Twitter button every PR).

**Comment by benborgers** [comment]
Sounds good, thanks! 

Do you know why I’m not able to connect to Glow in iOS Safari?

**Comment by vpontis** [comment]
> Sounds good, thanks! 
> 
> 
> 
> Do you know why I’m not able to connect to Glow in iOS Safari? 

I think it may be due to the url length. I can look into it -- want to make a task and assign it to me? 

Not a blocker for merging since I think it'll work at NFToken.so

**Comment by vpontis** [comment]
Merging this since I think we want to have less time w/ merge conflicts.

**Comment by vpontis** [comment]
Oh signing in doesn't work since we say the domain is `nftoken.so` but it's actually the luma-dev domain. I can fix that in the future.

**Comment by benborgers** [comment]
Ahh that makes sense! Out of curiosity, where do we specify the domain?

**Pull request merged**
