### PR TITLE
Use LuxButton in more places

### PR DESCRIPTION
**Pull request by benborgers**

### CODE REVIEW

**Comment by benborgers** [comment]
https://github.com/glow-xyz/nftoken/blob/8772abbee2117feba187696ade16d7ec87798767/docs/pages/index.tsx#L123-L129

Is there a better way of making `<LuxButton />` large on desktop but small on mobile? This feels a bit hacky.

**Comment by vpontis** [comment]
> Is there a better way of making <LuxButton /> large on desktop but small on mobile? This feels a bit hacky.

Unfortunately not

**Review by vpontis — CHANGES_REQUESTED** [review]
It doesn't seem like the links are working

**Comment by vpontis** [comment]
I tried testing the buttons here: https://nftoken-git-lux-button.luma-dev.com/

Let's make sure to test changes before deploying them, especially since this website is now live.

**Comment by benborgers** [comment]
Oh no! I shot myself in the foot while moving over `LuxButton`. I need to bring over `LuxLink` which requires `ExternalLink` and `ComponentsOverridesContext`, which feels like it could be too much to bring over at the moment (especially introducing the context provider). Where do you think we should draw the line?

**Comment by vpontis** [comment]
I think we don't want to bring over `ComponentsOverridesContext` but we can bring over `LuxLink` — does that work?

**Comment by benborgers** [comment]
Looks like `useComponentsOverrides` provides `Link` and `HOST`. Would it make sense to stub `useComponentsOverrides` for now so it just returns `Link` from `next/link` and `https://nftoken.so`?

**Comment by vpontis** [comment]
I don't think we should stub it, I think we should just put in `Link` and `https://nftoken.so` inline

**Comment by benborgers** [comment]
I went through and tested, and all links should be working now!

**Review by vpontis — APPROVED** [review]
Awesome!

**Pull request merged**
