### PR TITLE
Iterate on Create NFT section UI

### PR DESCRIPTION
**Pull request by benborgers**
[Screencast walkthrough (2 min)](https://share.cleanshot.com/XMFzJd)

### CODE REVIEW

**Comment by benborgers** [comment]
@vpontis re: https://github.com/glow-xyz/nftoken/pull/89#pullrequestreview-1002929049

> when you upload an image, are we actually uploading it to S3? should we? there might be some CORS issues but I can help with that. also, maybe we can style the image upload similar to how we do with <AvatarUploadField /> but make it square rather than round. NFTs should be square so we can crop them with getImageUrl

Not uploading to S3 at the moment, since I wasn’t sure how to get that hooked up. I’ve un-rounded the preview image to make it more similar to the actual NFT. 

Should I crop the image to be square aspect ratio? I could copy over getImageUrl from Luma’s codebase, or just crop it using CSS.

**Comment by vpontis** [comment]
Yea let's copy over `getImageUrl` and crop it to be square

**Comment by benborgers** [comment]
@vpontis I’ve updated it so that the image is cropped square via `getImageUrl`! Note that the image isn’t actually being uploaded to S3, it’s just a placeholder image for now.

**Comment by vpontis** [comment]
I'll add the S3 upload shortly 👍

**Pull request merged**
