### PR TITLE
Minting success animation

### PR DESCRIPTION
**Pull request by benborgers**
Two options for confetti: 

1. https://share.cleanshot.com/0KIJoP
2. https://share.cleanshot.com/9JlXAB

Any other things you’d want to see? The little “Your NFT has been minted!” message could be spiced up, but I’m not quite sure how.

### CODE REVIEW

**Review by vpontis — APPROVED** [review]
Maybe streaming from the top of the screen and less shooting kinda feel

**Comment by benborgers** [comment]
Did some tweaking; what do you think of this? https://share.cleanshot.com/N0EhWy

**Comment by vpontis** [comment]
Looks ok! I think we don't want to change the size of the well on success if we can avoid it. 

Also, I have a preference to use the same libraries that we use in the main Luma repo — so for animation, I'd like to use Framer Motion. You don't need to change this now, but it's something to keep in mind.

**Comment by benborgers** [comment]
Done! The size of the demo doesn’t change anymore, and I added a transition into the success state. 

https://share.cleanshot.com/H85nVi

**Pull request merged**
