### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by benborgers**
Draft until I can confirm that #85 and #89 work in dark mode.

### CODE REVIEW

**Review by vpontis — CHANGES_REQUESTED** [review]
I think I already did a PR that makes it support dark mode in `_document.tsx` last night

**Comment by benborgers** [comment]
Oops! My bad

**Comment by vpontis** [comment]
@benborgers we still don't want to use white or non dark mode supporting colors tho :)

**Comment by benborgers** [comment]
@vpontis Right! I’ll send a PR with fixes to CSS

**Pull request closed without merging**
